kadi:
  main_url: https://kadi4mat.greenbattnutzung.iwf.ing.tu-bs.de/
  records_url: api/records
  token_hash: ""
  token_name: ""
  token_expire: ""
  token_auth: pat

data:
  save_path: ./data
  plot_path: ./plots/