kadi:
  main_url: https://kadi4mat.greenbattnutzung.iwf.ing.tu-bs.de/
  records_url: api/records
  token_hash: 3b911948c5e481b5d4344d692af2e6c98ce80201d284107e
  token_name: bald_pull
  token_expire: 21-12-2021
  token_auth: pat

data:
  xlsx_path: ./example_data/BALd-SAMSUNG-35E-671_5..xlsx
  txt_path: ./example_data/LiFun002_T35_C40dch.txt